version: "3.0"
#==========================SERVICES=========================
services:
  #----------------------------PGSQL--------------------------
  db:
    image: postgres:latest
    container_name: realworld-db
    ports:
      - 5432:5432
    volumes:
      - ./volumes/realworld:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
